import type { Tutor } from '@/lib/types';

export const tutors: Tutor[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    avatarId: '1',
    subject: 'Physics',
    subjects: ['Physics', 'Mathematics'],
    headline: 'PhD in Physics with 10+ years of teaching experience.',
    bio: 'I specialize in making complex physics concepts understandable and engaging. My approach is patient and tailored to each student\'s learning style. I have a PhD from MIT and have helped hundreds of students excel in their physics courses.',
    qualifications: ['PhD in Physics, MIT', 'M.S. in Applied Mathematics', 'Certified High School Teacher'],
    experience: '12 years of tutoring and classroom teaching at high school and university levels.',
    rating: 4.9,
    pricePerHour: 75,
    availability: 'Full-time',
    reviews: [
      { id: 'r1', name: 'Alex Johnson', avatar: 'A', rating: 5, comment: 'Dr. Reed is amazing! She helped me understand quantum mechanics like no one else could.' },
      { id: 'r2', name: 'Samantha Lee', avatar: 'S', rating: 5, comment: 'Her sessions are well-structured and she is very patient. Highly recommended!' },
    ],
  },
  {
    id: '2',
    name: 'Ben Carter',
    avatarId: '2',
    subject: 'Mathematics',
    subjects: ['Mathematics', 'Computer Science'],
    headline: 'Software Engineer & Math Whiz, making math fun and accessible.',
    bio: 'As a software engineer, I use math every day. I love showing students the real-world applications of mathematics, from algebra to calculus. My goal is to build strong foundational skills and confidence.',
    qualifications: ['B.S. in Computer Science, Stanford', '8 years as a Software Engineer', 'Code.org Certified Instructor'],
    experience: '5 years of part-time tutoring for middle school to college students.',
    rating: 4.8,
    pricePerHour: 60,
    availability: 'Part-time',
    reviews: [
      { id: 'r3', name: 'Michael Brown', avatar: 'M', rating: 5, comment: 'Ben makes math make sense. I finally passed my calculus class because of him.' },
    ],
  },
  {
    id: '3',
    name: 'Chloe Davis',
    avatarId: '3',
    subject: 'English',
    subjects: ['English', 'History'],
    headline: 'Literature graduate passionate about essay writing and critical analysis.',
    bio: 'I help students find their voice and articulate their ideas clearly. From Shakespeare to contemporary literature, I can help with reading comprehension, essay structure, and creative writing.',
    qualifications: ['M.A. in English Literature, Oxford University', 'Published author of short stories'],
    experience: '6 years of experience in writing centers and as a private English tutor.',
    rating: 4.9,
    pricePerHour: 55,
    availability: 'Weekends only',
    reviews: [
      { id: 'r4', name: 'Emily White', avatar: 'E', rating: 5, comment: 'Chloe is a fantastic writing coach. My grades on essays have improved dramatically.' },
      { id: 'r5', name: 'David Green', avatar: 'D', rating: 5, comment: 'She helped me prepare for my AP Lit exam and I got a 5!' },
    ],
  },
  {
    id: '4',
    name: 'Dr. Marco Rossi',
    avatarId: '4',
    subject: 'Chemistry',
    subjects: ['Chemistry', 'Biology'],
    headline: 'Former university professor specializing in Organic and Inorganic Chemistry.',
    bio: 'With a long career in academia, I have a deep understanding of chemistry. I enjoy breaking down difficult topics into manageable parts and helping students prepare for exams like the MCAT.',
    qualifications: ['PhD in Chemistry, Cambridge', '20 years as a University Professor', 'MCAT Prep Specialist'],
    experience: '20+ years of teaching and tutoring.',
    rating: 5.0,
    pricePerHour: 80,
    availability: 'Full-time',
    reviews: [
      { id: 'r6', name: 'Jessica Taylor', avatar: 'J', rating: 5, comment: 'An actual genius. Dr. Rossi is the best chemistry tutor you can find, period.' },
    ],
  },
  {
    id: '5',
    name: 'Isabella Garcia',
    avatarId: '5',
    subject: 'Spanish',
    subjects: ['Spanish'],
    headline: 'Native Spanish speaker for immersive and effective language learning.',
    bio: '¡Hola! I offer immersive Spanish lessons for all levels. We will focus on conversation, grammar, and culture to make you a confident speaker. I was born and raised in Madrid, Spain.',
    qualifications: ['Native Spanish Speaker', 'DELE Certification Examiner', 'B.A. in Linguistics'],
    experience: '8 years of teaching Spanish to non-native speakers.',
    rating: 4.8,
    pricePerHour: 45,
    availability: 'Part-time',
    reviews: [
        { id: 'r7', name: 'Tom Clark', avatar: 'T', rating: 5, comment: 'Isabella is so friendly and makes learning Spanish fun. My conversational skills have improved so much.' },
    ],
  },
  {
    id: '6',
    name: 'Samuel Jones',
    avatarId: '6',
    subject: 'History',
    subjects: ['History'],
    headline: 'History buff who brings the past to life.',
    bio: 'I believe history is a story waiting to be told. I help students connect with historical events, understand their context, and analyze primary sources. My sessions are interactive and discussion-based.',
    qualifications: ['M.A. in World History, Columbia University', 'Museum Curator Assistant'],
    experience: '7 years of tutoring AP World History, AP US History, and European History.',
    rating: 4.7,
    pricePerHour: 50,
    availability: 'Weekends only',
    reviews: [
        { id: 'r8', name: 'Olivia Martinez', avatar: 'O', rating: 5, comment: 'Mr. Jones makes history so interesting! I actually look forward to our sessions.' },
    ],
  },
    {
    id: '7',
    name: 'Aisha Khan',
    avatarId: '7',
    subject: 'Biology',
    subjects: ['Biology', 'Chemistry'],
    headline: 'Medical student passionate about life sciences.',
    bio: 'As a current medical student, I have a strong grasp of biology and chemistry. I can help with high school and introductory college-level courses, as well as pre-med advising.',
    qualifications: ['Enrolled in M.D. Program, Johns Hopkins', 'B.S. in Molecular Biology', 'Lab Research Experience'],
    experience: '4 years of peer tutoring and private tutoring.',
    rating: 4.9,
    pricePerHour: 65,
    availability: 'Part-time',
    reviews: [
      { id: 'r9', name: 'Liam Wilson', avatar: 'L', rating: 5, comment: 'Aisha is incredibly smart and explains things really well. She\'s a great mentor for anyone interested in medicine.' },
    ],
  },
  {
    id: '8',
    name: 'Kenji Tanaka',
    avatarId: '8',
    subject: 'Computer Science',
    subjects: ['Computer Science', 'Mathematics'],
    headline: 'Full-stack developer with a knack for teaching algorithms and data structures.',
    bio: 'I enjoy mentoring aspiring programmers. I can help you with Python, JavaScript, data structures, algorithms, and preparing for technical interviews. Let\'s build something cool together!',
    qualifications: ['Lead Developer at a Tech Startup', 'B.S. in Computer Engineering', 'Expert in Python & JavaScript'],
    experience: '6 years in the tech industry and 3 years of coding boot camp instruction.',
    rating: 4.9,
    pricePerHour: 70,
    availability: 'Full-time',
    reviews: [
      { id: 'r10', name: 'Sophia Rodriguez', avatar: 'S', rating: 5, comment: 'Kenji helped me nail my technical interviews. His explanations of complex algorithms are the best.' },
    ],
  }
];
